### ISSUE TITLE
Change style of each radio button?

### ISSUE THREAD

**Issue by hristowwe** [WrathChaos/react-native-animated-radio-button-group#176]
![image](https://user-images.githubusercontent.com/57602380/168469178-28b108b4-e6c7-41bf-928d-6d909007c558.png)
Hi, I want to ask how could I change the style of the radio button to look something like this? Is it possible? Thank you for great lib!!

**Comment by WrathChaos** [comment]
Hello @hristowwe,
Thank you for kind words :)

I believe that [react-native-bouncy-checkbox-group](https://github.com/WrathChaos/react-native-bouncy-checkbox-group) library is better for your UI. You can customize it however you like :)

**Comment by hristowwe** [comment]
Thank you!!
