### ISSUE TITLE
WARNING: `useNativeDriver` was not specified. 

### ISSUE THREAD

**Issue by melihmuratpesmen** [WrathChaos/react-native-animated-radio-button-group#3]
![Simulator Screen Shot - iPhone 11 - 2021-04-01 at 01 45 04](https://user-images.githubusercontent.com/33424490/113220512-f85ebd80-928b-11eb-8baf-5fdaa44731cf.png)

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by WrathChaos** [comment]
Hello @melihmuratpesmen,
Thank you for reporting this :) I will fix it asap

**Comment by thebaddie** [comment]
I came here searching for a fix to this, so UP

**Comment by WrathChaos** [comment]
Hey guys,
@thebaddie @melihmuratpesmen 

The newest version of 1.0.0 is here :) I've rewritten with Typescript and `react-native-animated-button` is re-written with Typescript. These are completely new. Please check it out and open an issue if you need something else :)

Thank you!
